### ISSUE TITLE
Improve parse performance

### ISSUE THREAD

**Issue by princjef** [princjef/font-ligatures#2]
For this package to be useful in the context of xterm.js, it needs to be able to parse a full screen worth of text in a short enough time for both it and the rest of the render logic to run in enough time to fit within the time to render a single frame (16.7 or 33.3ms depending on whether it's 60 or 30 fps).

To leave enough time for the renderer to do its thing, we should shoot for parsing all of the text on the screen (line by line) in no more than 5ms and hopefully more like 1-3ms. If we assume a large buffer of 150 columns by 60 rows, we need to be able to parse 9000 characters in 5ms, or about 0.56 microseconds per character.

At the moment I'm seeing numbers ranging anywhere from 0.4 microseconds to 147 microseconds, so there's quite a bit of optimizing to do.

Related: https://github.com/xtermjs/xterm.js/issues/958

**Comment by princjef** [comment]
Initial benchmark numbers (all numbers are times in ms):

NAME                         | AVG    |  STDEV   | 5%     | 50%     | 95%     | AVG (CHAR) | STDEV (CHAR)
----------------------- | ------- | --------- | ------ | -------- | ------- | ------------- | ----------------
Fira Code: code.txt          | 5.9570  | 12.6951 | 0.5270  | 5.1020   | 12.2330  | **0.1443531**   | 0.2091743
Fira Code: noLigatures.txt   | 12.1932 | 3.4402  | 8.1420  | 12.1205  | 15.5900  | **0.1321094**   | 0.0334362
Iosevka: code.txt            | 0.5571  | 1.4722  | 0.0485  | 0.3215   | 1.6155   | **0.0135005**   | 0.0333483
Iosevka: noLigatures.txt     | 0.7476  | 0.4230  | 0.4365  | 0.6030   | 1.7725   | **0.0080998**   | 0.0044501
Monoid: code.txt             | 0.8896  | 1.6637  | 0.0910  | 0.6625   | 1.9225   | **0.0215566**   | 0.0482166
Monoid: noLigatures.txt      | 1.6661  | 0.6935  | 1.0695  | 1.4450   | 2.6910   | **0.0180521**   | 0.0071922
Ubuntu Mono: code.txt        | 0.0402  | 0.3935  | 0.0080  | 0.0220   | 0.0605   | **0.0009735**   | 0.0090228
Ubuntu Mono: noLigatures.txt | 0.0356   | 0.0644   | 0.0120  | 0.0280   | 0.0805   | **0.0003858**   | 0.0006891

**Comment by princjef** [comment]
This benchmark data can be regenerated by running `npm run bench`

**Comment by j-f1** [comment]
How much would caching help? i.e. if I hit enter, all of the lines will be the same except for the new one.

**Comment by princjef** [comment]
That's a good point. For the use case of a terminal (particularly when a user is inputting something), very few of the lines will actually change each time. You could potentially improve the benefits of caching further by calling it with each group of same-styled text rather than each line because the kinds of things that typically generate ligatures will often appear by themselves.

Biggest question is whether that optimization belongs in this library or in whoever is calling it. If it goes in here I'll probably disable it in the benchmark because I'm looping over a series of lines of text repeatedly.

**Comment by j-f1** [comment]
> You could potentially improve the benefits of caching further by calling it with each group of same-styled text rather than each line

also because ligatures won’t work if the characters are different colors.

**Comment by princjef** [comment]
Yeah the main thing against splitting them up further is that doing groups that are too small can actually be bad for perf. There's a certain base cost associated with making the call in the first case. If you look at the two lines for Ubuntu Mono in the chart, they are:

code.txt: **0.0009735 ms/char**
noLigatures.txt: **0.0003858 ms/char**

Since Ubuntu Mono has no ligatures, the only real difference between these two is that the second one has uniform length lines of ~80-100 characters whereas the lines in the first one are much more variable and probably less than half that length on average.

**Comment by princjef** [comment]
Looks like my computer was a little labored when running the initial tests. With all of the merged PRs, these are the new benchmarks. Besides the speedup from my computer this morning, the biggest gains are on the fonts with no ligatures (about 10x overall). I think we can call those good enough and turn attention to the actual ligature parsing.

NAME                          | AVG     | STDEV   | 5%      | 50%     | 95%     | AVG (CHAR)  | STDEV (CHAR)
------------------------ | -------- | -------- | ------- | ------- | -------- | -------------- | -------------
Fira Code: code.txt           | 2.5205  | 4.4478  | 0.2110  | 2.2315  | 5.3105  | **0.0610785**   | 0.0732810
Fira Code: noLigatures.txt    | 5.1131  | 0.9892  | 3.7050  | 5.0210  | 6.7075  | **0.0553995**   | 0.0087395
Iosevka: code.txt             | 0.2248  | 0.6206  | 0.0190  | 0.1345  | 0.6815  | **0.0054466**   | 0.0111357
Iosevka: noLigatures.txt      | 0.3197  | 0.1741  | 0.1960  | 0.2580  | 0.7780  | **0.0034637**   | 0.0018432
Monoid: code.txt             | 0.3771  | 0.7126  | 0.0390  | 0.2775  | 0.8730  | **0.0091377**   | 0.0171408
Monoid: noLigatures.txt       | 0.6856  | 0.2362  | 0.4405  | 0.6040  | 1.1365  | **0.0074278**   | 0.0024179
Ubuntu Mono: code.txt         | 0.0018  | 0.0116  | 0.0010  | 0.0010  | 0.0020  | **0.0000436**   | 0.0001726
Ubuntu Mono: noLigatures.txt  | 0.0015  | 0.0023  | 0.0010  | 0.0010  | 0.0020  | **0.0000165**   | 0.0000246

**Comment by Tyriar** [comment]
@princjef what does the caching look like at the moment? I was envisioning you would load a font which takes some time (up to a second?) which would pull all the ligature combinations out and that could be stored in an array. So after loading a font you would have something like this:

```ts
var fontCache: {
  'Fira Code': [
    '-->',
    '===',
    // etc.
  ]
}
```

One you have that it's just a matter of splitting up the input string and searching for each ligature of which I'm sure there are plenty of algorithms out there to handle efficiently.

Also I disagree with caching at the line level, we stay away from that in xterm.js as it takes a lot of memory to store data against a full line's worth of text.

**Comment by princjef** [comment]
There is essentially no caching beyond the parsing of the font file at the moment. The only real caching I do right now is to determine the specific list of lookup/replacement rules to check for a given font.

> I was envisioning you would load a font which takes some time (up to a second?) which would pull all the ligature combinations out and that could be stored in an array.

This is what I was hoping to do when I first started writing this, but the way the replacements work make that difficult for a couple reasons:

 * Not all ligatures are fixed length. For example, the [arrow ligatures](https://be5invis.github.io/Iosevka/#ligations) in Iosevka (`<--`, `==>`, etc.) can form a ligature of arbitrary length. This works because replacements are applied based on the current glyph sequence (including previous changes), a certain scan position and the context of glyphs around it. The same replacement rule can be applied repeatedly to the same input depending on the context around the scan position as it advances.
 * Even ligatures that apply to a fixed sequence of text will often depend on context present around them. The ligatures that work with the kind of lookup you described are [type 4](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-4-ligature-substitution-subtable), but the code ligatures use [type 6](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-6-chaining-contextual-substitution-subtable) almost exclusively, which doesn't map as cleanly.

That being said, I do think the key to optimizing is to cache additional information upfront and possibly to do some transformations on the data to reduce the amount of traversing necessary. There are a couple I have my eye on specifically:

 * The font format tries to reduce file size by forcing you to bounce around between different subtables a decent amount in the hopes that they can be reused. It should be pretty easy to flatten most of these to get more direct replacements
 * We can prune the lookup list by mapping each input that starts a sequence with a replacement rule to the list of lookup rules to which it applies. This should make sequences with no ligatures run much faster and allow us to reduce the amount of time spent searching useless lookups

> Also I disagree with caching at the line level, we stay away from that in xterm.js as it takes a lot of memory to store data against a full line's worth of text.

Wouldn't this only become a problem if we kept a large cache? If the focus was on optimizing repeated calls for minor changes to what is essentially the same screen, we could keep an lru cache of 50-100 lines and be able to use the cache effectively without keeping a large amount of memory locked up.

**Comment by Tyriar** [comment]
> Wouldn't this only become a problem if we kept a large cache? If the focus was on optimizing repeated calls for minor changes to what is essentially the same screen, we could keep an lru cache of 50-100 lines and be able to use the cache effectively without keeping a large amount of memory locked up.

You might be right, the benchmark(s) should let us know :+1:

**Comment by princjef** [comment]
I've completely rewritten the parsing/replacement logic in #6 to pre-generate a lookup tree for each lookup group in the font. It's still processed character by character, but processing each character is now about as fast as I think I can make it for the base algorithm (sans some minor tweaks). This nets about a 10x improvement across the board for fonts with ligatures.

The biggest drain on performance at this point is the sheer number of lookup rules in some fonts. Rules are grouped into lookups, which run in the order that they are defined. Each rule must be run against the full list of characters before the next lookup starts, and may change glyphs that are used as inputs to following lookups.

I don't know of a reasonable way to combine the lookups without immense complexity, so I still iterate over the full list of glyphs for each lookup separately. You can see the impact of this pretty clearly with the three ligatured fonts I benchmark against:

Font | Lookup Count | Performance (ms/char)
---- | ---------------- | ---------------------
Fira Code | 134 | 0.0090939
Iosevka | 21 | 0.0020303
Monoid | 1 | 0.0011164

There are a few more optimizations I still have left but I'm approaching the bottom of the well of significant optimizations before caching. Here's what I have left:

 * Build mapping of glyphs to the first lookup containing them
    * This has the potential to allow us to skip a lot of lookups and/or reduce the range of characters to scan for each lookup (particularly useful for ranges where the characters don't form ligatures)
    * This will have to be recomputed any time a lookup performs a replacement, so if we're not careful it could end up harming performance in some cases (though I doubt it)
 * Combine ligature ranges as they're generated rather than adding them all to an array and merging at the end
    * This is probably going to be pretty minor. I'll probably do stuff like pick the fastest loops, etc. at the same time
 * Cache a certain number of previous lines
    * Going to do this after other optimizations and will add memory information to benchmark as part of it

**Comment by Tyriar** [comment]
@princjef I'm a little confused by the numbers, does 0.0001 ~= 1ms or is the AVG column measured in milliseconds? If it's the latter, the "Fira Code: code (cache)" column which I imagine will be 0.0007724*100*60=4.6344ms for a 100x60 terminal (pretty small really). This is a very long time just to compute details on the text, most of the CPU need to be reserved for parsing and rendering to ensure a good experience.

Am I reading the numbers wrong?

**Comment by j-f1** [comment]
@Tyriar Don’t forget that most<sup>[*citation needed*]</sup> of that terminal is empty space.

**Comment by princjef** [comment]
@Tyriar Your reading of the numbers is correct. I have been using 10k characters as my reference for the size of a large terminal (or 7.7ms for the example you chose). Fira Code in particular has been challenging to optimize, but I'm counting on most cases where there is a lot of text coming really fast either being able to lean heavily on the cache or not having many/any ligatures (which is faster to compute).

There are also a couple of things about the benchmark numbers that can be a little misleading:

 * As mentioned previously, the cached runs actually do a full uncached run through the input in addition to the cached ones. This skews the numbers higher and makes it hard to determine how fast things would actually be under cached scenarios. I have fixed this in the code and the numbers below reflect that.
 * The first call (cached or uncached) is *very* slow compared to the rest. I'm assuming this is because the first call is unoptimized. The previous numbers were based on 1000 iterations of each test, which wasn't enough to really mask the impact of that first call. I've bumped it up to 10,000 to reduce the importance of the first call as that will be more indicative of the normal operation.

Here are the numbers with the aforementioned changes:

NAME                              | AVG (CHAR)
--------------------------------- | ---------- 
Fira Code: code                   | 0.0008904  
Fira Code: no-ligatures           | 0.0002920  
Fira Code: code (cache)           | 0.0000487  
Fira Code: no-ligatures (cache)   | 0.0000197  
Iosevka: code                     | 0.0002596  
Iosevka: no-ligatures             | 0.0001113  
Iosevka: code (cache)             | 0.0000452  
Iosevka: no-ligatures (cache)     | 0.0000210  
Monoid: code                      | 0.0001728  
Monoid: no-ligatures              | 0.0001098  
Monoid: code (cache)              | 0.0000392  
Monoid: no-ligatures (cache)      | 0.0000252  
Ubuntu Mono: code                 | 0.0000386  
Ubuntu Mono: no-ligatures         | 0.0000164  
Ubuntu Mono: code (cache)         | 0.0000445  
Ubuntu Mono: no-ligatures (cache) | 0.0000169

Fira Code is still ~9ms uncached, but is more like 0.5ms with cache. The only substantive optimization I can think to make is to combine the separate lookup groups in fonts like Fira Code and Iosevka to make them look and act more like Monoid. However, that is much more complicated than anything I've done so far and still can't be fully generalized because Iosevka makes use of some lookups that have to be processed in the opposite direction of everything else.

**Comment by Tyriar** [comment]
Those number looks way better.

Also is the caching based purely on lines? ie. `cache: { [someLine: string]: Result }`

**Comment by Tyriar** [comment]
@j-f1 yep, white space should definitely be ignored 👍

**Comment by princjef** [comment]
@Tyriar in the case of these benchmarks, yes. It caches the result for whatever input you give it

**Comment by princjef** [comment]
I'm considering this done for now. If there are more optimizations needed in the future, we can open a new issue.
